### ISSUE TITLE
Suggestion - World Spawn

### ISSUE THREAD

**Issue by Time6628** [Vastrix/Offline-Teleporter#2]
How about a command that we can use from the console like /otpspawn which teleports the player to the world spawn? :smiley: 
-Time

**Comment by Vastrix** [comment]
Upon logging in or when the player is online? :o

**Comment by Time6628** [comment]
Upon login :o

**Comment by Vastrix** [comment]
Great idea! :)

However I'm currently bussy doing other important stuff ;(
So support for this plugin is atm very limited (when things were to break all of a sudden i'd still fix it for example..)

But if I'm back, i'll certainly add it to the new release! :)

Thanks for the feedback!

**Comment by RoboMWM** [comment]
Great idea! I'll implement it later!

*closes issue*

>_>

**Comment by Willsr71** [comment]
It is actually implemented in the latest version, but yeah still

**Comment by Vastrix** [comment]
@RoboMWM 
Feel free to send a Push request, if it's half-decently written and the code works i'll most definitely accept it and add you as a collaborator... :)

I started this project when I was in middle school, now that I'm in college, i just don't have any time at all.. :S

**Comment by RoboMWM** [comment]
I might, I stopped using this plugin though since I've had almost no need to use it (I was thinking of using it either for security purposes or rescuing players that were stuck, but most of the time they end up finding their own way to solve it or just die :/

Either way I wasn't totally aware of the date this was made and made my comment haphazardly, sorry about that; nor am I interested in this feature - but I could see it being useful in instances where someone resets a world but keeps playerData so they're at spawn when they join next time(?) so I'll take a look at it once I get some free time to do so - and probably refactor the nested if statements :P

**Comment by Vastrix** [comment]
@RoboMWM yea, a case statement or a dictionary with {"command": function} would've been better..
I was young and foolish :P 

I should rewrite the core.. Wish I had the time..

**Comment by Time6628** [comment]
I can work on it when I get a chance :D

**Comment by Time6628** [comment]
I've begun working on a Forge port of it: https://github.com/Time6628/Offline-Teleporter-Forge.

**Comment by Vastrix** [comment]
@Time6628 
This plugin should be forge/mystcraft compatible no? :o 
If so, I don't really see the need, but feel free to (ofc).. :)

**Comment by Time6628** [comment]
@Vastrix Yes.The way I'm doing it is by changing the player's location directly instead of teleporting them when they login.

**Comment by Vastrix** [comment]
@Time6628 ah yea, Forge does indeed support player.dat editing directly iirc :)
